using System;
using System.ComponentModel;

namespace server.Helpers
{

    [AttributeUsage(AttributeTargets.Field)]
    public class CountryInfoAttribute : Attribute
    {
        public string NamePL { get; }
        public string NameEN { get; }

        public CountryInfoAttribute(string namePL, string nameEN)
        {
            NamePL = namePL;
            NameEN = nameEN;
        }
    }
    public enum CountryCode
    {
        [CountryInfo("Afganistan", "Afghanistan")] AF,
        [CountryInfo("Albania", "Albania")] AL,
        [CountryInfo("Algieria", "Algeria")] DZ,
        [CountryInfo("Andora", "Andorra")] AD,
        [CountryInfo("Angola", "Angola")] AO,
        [CountryInfo("Anguilla", "Anguilla")] AI,
        [CountryInfo("Antarktyka", "Antarctica")] AQ,
        [CountryInfo("Antigua i Barbuda", "Antigua and Barbuda")] AG,
        [CountryInfo("Arabia Saudyjska", "Saudi Arabia")] SA,
        [CountryInfo("Argentyna", "Argentina")] AR,
        [CountryInfo("Armenia", "Armenia")] AM,
        [CountryInfo("Aruba", "Aruba")] AW,
        [CountryInfo("Australia", "Australia")] AU,
        [CountryInfo("Austria", "Austria")] AT,
        [CountryInfo("Azerbejdżan", "Azerbaijan")] AZ,
        [CountryInfo("Bahamy", "Bahamas")] BS,
        [CountryInfo("Bahrajn", "Bahrain")] BH,
        [CountryInfo("Bangladesz", "Bangladesh")] BD,
        [CountryInfo("Barbados", "Barbados")] BB,
        [CountryInfo("Belgia", "Belgium")] BE,
        [CountryInfo("Belize", "Belize")] BZ,
        [CountryInfo("Benin", "Benin")] BJ,
        [CountryInfo("Bermudy", "Bermuda")] BM,
        [CountryInfo("Bhutan", "Bhutan")] BT,
        [CountryInfo("Białoruś", "Belarus")] BY,
        [CountryInfo("Boliwia", "Bolivia, Plurinational State of")] BO,
        [CountryInfo("Bonaire, Sint Eustatius i Saba", "Bonaire, Sint Eustatius and Saba")] BQ,
        [CountryInfo("Bośnia i Hercegowina", "Bosnia and Herzegovina")] BA,
        [CountryInfo("Botswana", "Botswana")] BW,
        [CountryInfo("Brazylia", "Brazil")] BR,
        [CountryInfo("Brunei", "Brunei Darussalam")] BN,
        [CountryInfo("Brytyjskie Terytorium Oceanu Indyjskiego", "British Indian Ocean Territory")] IO,
        [CountryInfo("Brytyjskie Wyspy Dziewicze", "Virgin Islands, British")] VG,
        [CountryInfo("Bułgaria", "Bulgaria")] BG,
        [CountryInfo("Burkina Faso", "Burkina Faso")] BF,
        [CountryInfo("Burundi", "Burundi")] BI,
        [CountryInfo("Chile", "Chile")] CL,
        [CountryInfo("Chiny", "China")] CN,
        [CountryInfo("Chorwacja", "Croatia")] HR,
        [CountryInfo("Curaçao", "Curaçao")] CW,
        [CountryInfo("Cypr", "Cyprus")] CY,
        [CountryInfo("Czad", "Chad")] TD,
        [CountryInfo("Czarnogóra", "Montenegro")] ME,
        [CountryInfo("Czechy", "Czech Republic")] CZ,
        [CountryInfo("Dalekie Wyspy Mniejsze Stanów Zjednoczonych", "United States Minor Outlying Islands")] UM,
        [CountryInfo("Dania", "Denmark")] DK,
        [CountryInfo("Demokratyczna Republika Konga", "Congo, the Democratic Republic of the")] CD,
        [CountryInfo("Dominika", "Dominica")] DM,
        [CountryInfo("Dominikana", "Dominican Republic")] DO,
        [CountryInfo("Dżibuti", "Djibouti")] DJ,
        [CountryInfo("Egipt", "Egypt")] EG,
        [CountryInfo("Ekwador", "Ecuador")] EC,
        [CountryInfo("Erytrea", "Eritrea")] ER,
        [CountryInfo("Estonia", "Estonia")] EE,
        [CountryInfo("Etiopia", "Ethiopia")] ET,
        [CountryInfo("Falklandy", "Falkland Islands (Malvinas)")] FK,
        [CountryInfo("Fidżi", "Fiji")] FJ,
        [CountryInfo("Filipiny", "Philippines")] PH,
        [CountryInfo("Finlandia", "Finland")] FI,
        [CountryInfo("Francja", "France")] FR,
        [CountryInfo("Francuskie Terytoria Południowe i Antarktyczne", "French Southern Territories")] TF,
        [CountryInfo("Gabon", "Gabon")] GA,
        [CountryInfo("Gambia", "Gambia")] GM,
        [CountryInfo("Georgia Południowa i Sandwich Południowy", "South Georgia and the South Sandwich Islands")] GS,
        [CountryInfo("Ghana", "Ghana")] GH,
        [CountryInfo("Gibraltar", "Gibraltar")] GI,
        [CountryInfo("Grecja", "Greece")] GR,
        [CountryInfo("Grenada", "Grenada")] GD,
        [CountryInfo("Grenlandia", "Greenland")] GL,
        [CountryInfo("Gruzja", "Georgia")] GE,
        [CountryInfo("Guam", "Guam")] GU,
        [CountryInfo("Guernsey", "Guernsey")] GG,
        [CountryInfo("Gujana Francuska", "French Guiana")] GF,
        [CountryInfo("Gujana", "Guyana")] GY,
        [CountryInfo("Gwadelupa", "Guadeloupe")] GP,
        [CountryInfo("Gwatemala", "Guatemala")] GT,
        [CountryInfo("Gwinea Bissau", "Guinea-Bissau")] GW,
        [CountryInfo("Gwinea Równikowa", "Equatorial Guinea")] GQ,
        [CountryInfo("Gwinea", "Guinea")] GN,
        [CountryInfo("Haiti", "Haiti")] HT,
        [CountryInfo("Hiszpania", "Spain")] ES,
        [CountryInfo("Holandia", "Netherlands")] NL,
        [CountryInfo("Honduras", "Honduras")] HN,
        [CountryInfo("Hongkong", "Hong Kong")] HK,
        [CountryInfo("Indie", "India")] IN,
        [CountryInfo("Indonezja", "Indonesia")] ID,
        [CountryInfo("Irak", "Iraq")] IQ,
        [CountryInfo("Iran", "Iran, Islamic Republic of")] IR,
        [CountryInfo("Irlandia", "Ireland")] IE,
        [CountryInfo("Islandia", "Iceland")] IS,
        [CountryInfo("Izrael", "Israel")] IL,
        [CountryInfo("Jamajka", "Jamaica")] JM,
        [CountryInfo("Japonia", "Japan")] JP,
        [CountryInfo("Jemen", "Yemen")] YE,
        [CountryInfo("Jersey", "Jersey")] JE,
        [CountryInfo("Jordania", "Jordan")] JO,
        [CountryInfo("Kajmany", "Cayman Islands")] KY,
        [CountryInfo("Kambodża", "Cambodia")] KH,
        [CountryInfo("Kamerun", "Cameroon")] CM,
        [CountryInfo("Kanada", "Canada")] CA,
        [CountryInfo("Katar", "Qatar")] QA,
        [CountryInfo("Kazachstan", "Kazakhstan")] KZ,
        [CountryInfo("Kenia", "Kenya")] KE,
        [CountryInfo("Kirgistan", "Kyrgyzstan")] KG,
        [CountryInfo("Kiribati", "Kiribati")] KI,
        [CountryInfo("Kolumbia", "Colombia")] CO,
        [CountryInfo("Komory", "Comoros")] KM,
        [CountryInfo("Kongo", "Congo")] CG,
        [CountryInfo("Korea Południowa", "Korea, Republic of")] KR,
        [CountryInfo("Korea Północna", "Korea, Democratic People's Republic of")] KP,
        [CountryInfo("Kostaryka", "Costa Rica")] CR,
        [CountryInfo("Kuba", "Cuba")] CU,
        [CountryInfo("Kuwejt", "Kuwait")] KW,
        [CountryInfo("Laos", "Lao People's Democratic Republic")] LA,
        [CountryInfo("Lesotho", "Lesotho")] LS,
        [CountryInfo("Liban", "Lebanon")] LB,
        [CountryInfo("Liberia", "Liberia")] LR,
        [CountryInfo("Libia", "Libyan Arab Jamahiriya")] LY,
        [CountryInfo("Liechtenstein", "Liechtenstein")] LI,
        [CountryInfo("Litwa", "Lithuania")] LT,
        [CountryInfo("Luksemburg", "Luxembourg")] LU,
        [CountryInfo("Łotwa", "Latvia")] LV,
        [CountryInfo("Macedonia", "Macedonia, the former Yugoslav Republic of")] MK,
        [CountryInfo("Madagaskar", "Madagascar")] MG,
        [CountryInfo("Majotta", "Mayotte")] YT,
        [CountryInfo("Makau", "Macao")] MO,
        [CountryInfo("Malawi", "Malawi")] MW,
        [CountryInfo("Malediwy", "Maldives")] MV,
        [CountryInfo("Malezja", "Malaysia")] MY,
        [CountryInfo("Mali", "Mali")] ML,
        [CountryInfo("Malta", "Malta")] MT,
        [CountryInfo("Mariany Północne", "Northern Mariana Islands")] MP,
        [CountryInfo("Maroko", "Morocco")] MA,
        [CountryInfo("Martynika", "Martinique")] MQ,
        [CountryInfo("Mauretania", "Mauritania")] MR,
        [CountryInfo("Mauritius", "Mauritius")] MU,
        [CountryInfo("Meksyk", "Mexico")] MX,
        [CountryInfo("Mikronezja", "Micronesia, Federated States of")] FM,
        [CountryInfo("Mjanma", "Myanmar")] MM,
        [CountryInfo("Mołdawia", "Moldova, Republic of")] MD,
        [CountryInfo("Monako", "Monaco")] MC,
        [CountryInfo("Mongolia", "Mongolia")] MN,
        [CountryInfo("Montserrat", "Montserrat")] MS,
        [CountryInfo("Mozambik", "Mozambique")] MZ,
        [CountryInfo("Namibia", "Namibia")] NA,
        [CountryInfo("Nauru", "Nauru")] NR,
        [CountryInfo("Nepal", "Nepal")] NP,
        [CountryInfo("Niemcy", "Germany")] DE,
        [CountryInfo("Niger", "Niger")] NE,
        [CountryInfo("Nigeria", "Nigeria")] NG,
        [CountryInfo("Nikaragua", "Nicaragua")] NI,
        [CountryInfo("Niue", "Niue")] NU,
        [CountryInfo("Norfolk", "Norfolk Island")] NF,
        [CountryInfo("Norwegia", "Norway")] NO,
        [CountryInfo("Nowa Kaledonia", "New Caledonia")] NC,
        [CountryInfo("Nowa Zelandia", "New Zealand")] NZ,
        [CountryInfo("Oman", "Oman")] OM,
        [CountryInfo("Pakistan", "Pakistan")] PK,
        [CountryInfo("Palau", "Palau")] PW,
        [CountryInfo("Palestyna", "Palestinian Territory, Occupied")] PS,
        [CountryInfo("Panama", "Panama")] PA,
        [CountryInfo("Papua-Nowa Gwinea", "Papua New Guinea")] PG,
        [CountryInfo("Paragwaj", "Paraguay")] PY,
        [CountryInfo("Peru", "Peru")] PE,
        [CountryInfo("Pitcairn", "Pitcairn")] PN,
        [CountryInfo("Polinezja Francuska", "French Polynesia")] PF,
        [CountryInfo("Polska", "Poland")] PL,
        [CountryInfo("Portoryko", "Puerto Rico")] PR,
        [CountryInfo("Portugalia", "Portugal")] PT,
        [CountryInfo("Republika Południowej Afryki", "South Africa")] ZA,
        [CountryInfo("Republika Środkowoafrykańska", "Central African Republic")] CF,
        [CountryInfo("Republika Zielonego Przylądka", "Cape Verde")] CV,
        [CountryInfo("Reunion", "Réunion")] RE,
        [CountryInfo("Rosja", "Russian Federation")] RU,
        [CountryInfo("Rumunia", "Romania")] RO,
        [CountryInfo("Rwanda", "Rwanda")] RW,
        [CountryInfo("Sahara Zachodnia", "Western Sahara")] EH,
        [CountryInfo("Saint Kitts i Nevis", "Saint Kitts and Nevis")] KN,
        [CountryInfo("Saint Lucia", "Saint Lucia")] LC,
        [CountryInfo("Saint Vincent i Grenadyny", "Saint Vincent and the Grenadines")] VC,
        [CountryInfo("Saint-Barthélemy", "Saint Barthélemy")] BL,
        [CountryInfo("Saint-Martin", "Saint Martin (French part)")] MF,
        [CountryInfo("Saint-Pierre i Miquelon", "Saint Pierre and Miquelon")] PM,
        [CountryInfo("Salwador", "El Salvador")] SV,
        [CountryInfo("Samoa Amerykańskie", "American Samoa")] AS,
        [CountryInfo("Samoa", "Samoa")] WS,
        [CountryInfo("San Marino", "San Marino")] SM,
        [CountryInfo("Senegal", "Senegal")] SN,
        [CountryInfo("Serbia", "Serbia")] RS,
        [CountryInfo("Seszele", "Seychelles")] SC,
        [CountryInfo("Sierra Leone", "Sierra Leone")] SL,
        [CountryInfo("Singapur", "Singapore")] SG,
        [CountryInfo("Sint Maarten", "Sint Maarten (Dutch part)")] SX,
        [CountryInfo("Słowacja", "Slovakia")] SK,
        [CountryInfo("Słowenia", "Slovenia")] SI,
        [CountryInfo("Somalia", "Somalia")] SO,
        [CountryInfo("Sri Lanka", "Sri Lanka")] LK,
        [CountryInfo("Stany Zjednoczone", "United States")] US,
        [CountryInfo("Suazi", "Swaziland")] SZ,
        [CountryInfo("Sudan", "Sudan")] SD,
        [CountryInfo("Sudan Południowy", "South Sudan")] SS,
        [CountryInfo("Surinam", "Suriname")] SR,
        [CountryInfo("Svalbard i Jan Mayen", "Svalbard and Jan Mayen")] SJ,
        [CountryInfo("Syria", "Syrian Arab Republic")] SY,
        [CountryInfo("Szwajcaria", "Switzerland")] CH,
        [CountryInfo("Szwecja", "Sweden")] SE,
        [CountryInfo("Tadżykistan", "Tajikistan")] TJ,
        [CountryInfo("Tajlandia", "Thailand")] TH,
        [CountryInfo("Tajwan", "Taiwan, Province of China")] TW,
        [CountryInfo("Tanzania", "Tanzania, United Republic of")] TZ,
        [CountryInfo("Timor Wschodni", "Timor-Leste")] TL,
        [CountryInfo("Togo", "Togo")] TG,
        [CountryInfo("Tokelau", "Tokelau")] TK,
        [CountryInfo("Tonga", "Tonga")] TO,
        [CountryInfo("Trynidad i Tobago", "Trinidad and Tobago")] TT,
        [CountryInfo("Tunezja", "Tunisia")] TN,
        [CountryInfo("Turcja", "Turkey")] TR,
        [CountryInfo("Turkmenistan", "Turkmenistan")] TM,
        [CountryInfo("Turks i Caicos", "Turks and Caicos Islands")] TC,
        [CountryInfo("Tuvalu", "Tuvalu")] TV,
        [CountryInfo("Uganda", "Uganda")] UG,
        [CountryInfo("Ukraina", "Ukraine")] UA,
        [CountryInfo("Urugwaj", "Uruguay")] UY,
        [CountryInfo("Uzbekistan", "Uzbekistan")] UZ,
        [CountryInfo("Vanuatu", "Vanuatu")] VU,
        [CountryInfo("Wallis i Futuna", "Wallis and Futuna")] WF,
        [CountryInfo("Watykan", "Holy See (Vatican City State)")] VA,
        [CountryInfo("Wenezuela", "Venezuela, Bolivarian Republic of")] VE,
        [CountryInfo("Węgry", "Hungary")] HU,
        [CountryInfo("Wielka Brytania", "United Kingdom")] GB,
        [CountryInfo("Wietnam", "Viet Nam")] VN,
        [CountryInfo("Włochy", "Italy")] IT,
        [CountryInfo("Wybrzeże Kości Słoniowej", "Côte d'Ivoire")] CI,
        [CountryInfo("Wyspa Bouveta", "Bouvet Island")] BV,
        [CountryInfo("Wyspa Bożego Narodzenia", "Christmas Island")] CX,
        [CountryInfo("Wyspa Man", "Isle of Man")] IM,
        [CountryInfo("Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
                    "Saint Helena, Ascension and Tristan Cunha")]
        SH,
        [CountryInfo("Wyspy Alandzkie", "Åland Islands")] AX,
        [CountryInfo("Wyspy Cooka", "Cook Islands")] CK,
        [CountryInfo("Wyspy Dziewicze Stanów Zjednoczonych", "Virgin Islands, U.S.")] VI,
        [CountryInfo("Wyspy Heard i McDonalda", "Heard Island and McDonald Islands")] HM,
        [CountryInfo("Wyspy Kokosowe", "Cocos (Keeling) Islands")] CC,
        [CountryInfo("Wyspy Marshalla", "Marshall Islands")] MH,
        [CountryInfo("Wyspy Owcze", "Faroe Islands")] FO,
        [CountryInfo("Wyspy Salomona", "Solomon Islands")] SB,
        [CountryInfo("Wyspy Świętego Tomasza i Książęca", "Sao Tome and Principe")] ST,
        [CountryInfo("Zambia", "Zambia")] ZM,
        [CountryInfo("Zimbabwe", "Zimbabwe")] ZW,
        [CountryInfo("Zjednoczone Emiraty Arabskie", "United Arab Emirates")] AE
    }
}